#!/usr/bin/env python
# license removed for brevity
# ROS
import rospy
import random as r
from std_msgs.msg import String
from std_msgs.msg import Bool

class CommandListener(object):
    
    def __init__(self):
        rospy.init_node('command_listener')
        
        while not rospy.is_shutdown():
            self.col = 'A'
            self.row = 5

            self.msg = "P" + str(self.col) + str(self.row)

            # Publishers
            self.pub = rospy.Publisher('chess/position', String, queue_size = 10)
            self.pub.publish(self.msg)

            # Subscribers
            rospy.Subscriber('chess/is_command_good', String, self.run_listener)
            rospy.Subscriber('chess/is_robot_ready', String, self.run_listener)

            rospy.Rate(1).sleep()
    
    def run_listener(self, data):
        pass


if __name__ == '__main__':
    CommandListener()